### ISSUE TITLE
TypeError: _get_source() takes at least 6 arguments (4 given) Creating Data Template XML

### ISSUE THREAD

**Issue by josegosuna** [JayVora-SerpentCS/Jasperv8#10]
Hello;

  I've got this error when I was trying to create a XML data template for JasperReports.

============ Error extract ====================================
File "/data/odoo/instancias/odoo/modules/jasper_reports/report_xml.py", line 225, in generate_xml
    'field', language)
  File "/data/odoo/instancias/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
TypeError: _get_source() takes at least 6 arguments (4 given)

===========FIX proposal:==========================================
jasper_reports/report_xml.py
line 224:
             if language:
                 # Obtain field string for user's language.
                 name = pool.get('ir.translation'
-                                )._get_source(modelName + ',' + field,
+                                )._get_source(self._cr, self._uid, modelName + ',' + field,
                                               'field', language)
             if not name:
                 # If there's not description in user's language,

======== Full Error ===================================

OpenERP Server Error
Traceback (most recent call last):
  File "/data/odoo/instancias/odoo/openerp/http.py", line 517, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/data/odoo/instancias/odoo/openerp/http.py", line 535, in dispatch
    result = self._call_function(*_self.params)
  File "/data/odoo/instancias/odoo/openerp/http.py", line 294, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/data/odoo/instancias/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/data/odoo/instancias/odoo/openerp/http.py", line 291, in checked_call
    return self.endpoint(_a, *_kw)
  File "/data/odoo/instancias/odoo/openerp/http.py", line 751, in __call__
    return self.method(_args, *_kw)
  File "/data/odoo/instancias/odoo/openerp/http.py", line 387, in response_wrap
    response = f(_args, *_kw)
  File "/data/odoo/instancias/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/data/odoo/instancias/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/data/odoo/instancias/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/data/odoo/instancias/odoo/openerp/api.py", line 360, in old_api
    result = method(recs, _args, *_kwargs)
  File "/data/odoo/instancias/odoo/modules/jasper_reports/wizard/jasper_create_data_template.py", line 48, in action_create_xml
    ].create_xml(model.model, data['depth'])
  File "/data/odoo/instancias/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/data/odoo/instancias/odoo/modules/jasper_reports/report_xml.py", line 318, in create_xml
    self.generate_xml(self.pool, model, recordNode, document, depth, True)
  File "/data/odoo/instancias/odoo/openerp/api.py", line 235, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/data/odoo/instancias/odoo/modules/jasper_reports/report_xml.py", line 225, in generate_xml
    'field', language)
  File "/data/odoo/instancias/odoo/openerp/api.py", line 237, in wrapper
    return old_api(self, _args, *_kwargs)
TypeError: _get_source() takes at least 6 arguments (4 given)
# 

I hope it helps

Jose

**Comment by miguelchuga** [comment]
:(

**Comment by miguelchuga** [comment]
+1  omarigdev27 :)
