### ISSUE TITLE
v12 EE error printing

### ISSUE THREAD

**Issue by davidogles** [JayVora-SerpentCS/Jasperv8#107]
Created template, imported into JasperSoft Studio 6.1.  build report and added it into odoo.  when i run the report, I get the following error in the log, but screen error window is blank:

    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 203, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo-server/odoo/http.py", line 835, in dispatch
    r = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/jasper_reports/controllers/main.py", line 58, in report_routes
    context).render_jasper(docids, data=data)
  File "/odoo/odoo-server/addons/jasper_reports/models/report_xml.py", line 177, in render_jasper
    jasper = r.execute()
  File "/odoo/odoo-server/addons/jasper_reports/JasperReports/jasper_report_config.py", line 177, in execute
    data_file, output_file, sub_report_data_files)
  File "/odoo/odoo-server/addons/jasper_reports/JasperReports/jasper_report_config.py", line 263, in execute_report
    connection_parameters, self.report_path, output_file, parameters)
  File "/odoo/odoo-server/addons/jasper_reports/JasperReports/jasper_server.py", line 115, in execute
    self.start()
  File "/odoo/odoo-server/addons/jasper_reports/JasperReports/jasper_server.py", line 102, in start
    process = subprocess.Popen(command, env=env, cwd=cwd)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'java': 'java'

thanks,
Dave

**Comment by davidogles** [comment]
this is my Java Path: 

/odoo/odoo-server/addons/jasper_reports/java
--

**Comment by davidogles** [comment]
didn't mean to close this

**Comment by JayVora-SerpentCS** [comment]
@hiren-serpentcs plz check

**Comment by hiren-serpentcs** [comment]
Hello, @davidogles 

Thanks for reporting this issue. 

Seems like the Java is not installed on your system, can you please check if the java is properly installed on the system or not?

Thanks.

**Comment by hiren-serpentcs** [comment]
Hi @JayVora-SerpentCS 

We can assume this is fixed and close the issue.

@davidogles you can reopen the issue if it's not fixed.
