### ISSUE TITLE
Error V11 Error Saving File

### ISSUE THREAD

**Issue by rjay1018** [JayVora-SerpentCS/Jasperv8#128]
Error:

                
                    
                        
                            
                                
                                    Home
                                    Back
                                
                            
                        
                    
                
                
                    
                        500: Internal Server Error
                    
                    

                    
                        
    
        
            
                
                    
                        Error
                    
                
            
            
                
                    
                    
                        Error message:
                        ("Report Error\n<Fault 0: 'Failed to invoke method execute in class com.nantic.jasperreports.JasperServer: Error saving file: /opt/odoo11/custom/addons/jasper_reports/custom_reports/SYCC Contract Rental Invoice.jasper.'>", '')
                    
                
            
        
        
        
            
                
                    
                        Traceback
                    
                
            
            
                
                    Traceback (most recent call last):
  File "/opt/odoo11/custom/addons/jasper_reports/JasperReports/jasper_server.py", line 108, in execute
    return self.proxy.Report.execute(*args)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1150, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1322, in parse_response
    return u.close()
  File "/usr/lib/python3.5/xmlrpc/client.py", line 655, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault 0: 'Failed to invoke method execute in class com.nantic.jasperreports.JasperServer: Error saving file: /opt/odoo11/custom/addons/jasper_reports/custom_reports/SYCC Contract Rental Invoice.jasper.'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo11/odoo-server/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/opt/odoo11/odoo-server/odoo/http.py", line 830, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo11/odoo-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo11/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo11/odoo-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo11/odoo-server/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo11/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo11/custom/addons/jasper_reports/controllers/main.py", line 55, in report_routes
    context).render_jasper(docids, data=data)
  File "/opt/odoo11/custom/addons/jasper_reports/report_xml.py", line 182, in render_jasper
    jasper = r.execute()
  File "/opt/odoo11/custom/addons/jasper_reports/jasper_report.py", line 203, in execute
    sub_report_data_files)
  File "/opt/odoo11/custom/addons/jasper_reports/jasper_report.py", line 291, in execute_report
    output_file, parameters)
  File "/opt/odoo11/custom/addons/jasper_reports/JasperReports/jasper_server.py", line 121, in execute
    raise UserError(_('Report Error\n%s' % e))
odoo.exceptions.UserError: ("Report Error\n<Fault 0: 'Failed to invoke method execute in class com.nantic.jasperreports.JasperServer: Error saving file: /opt/odoo11/custom/addons/jasper_reports/custom_reports/SYCC Contract Rental Invoice.jasper.'>", '')

                
            
        
    

                    
                
            

undefined

**Comment by rjay1018** [comment]
will mark this solved., seems like you need to have user permission causes the error..
