### ISSUE TITLE
I installed on odoo14 completely but when click print it show error PermissionError: [Errno 13] Permission denied: 'odoo-jasper.pid'

### ISSUE THREAD

**Issue by time2sales** [JayVora-SerpentCS/Jasperv8#132]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo14/odoo-custom-addons/jasper_reports/JasperReports/jasper_server.py", line 113, in execute
    return self.proxy.Report.execute(*args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1165, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1278, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1308, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo14/odoo-custom-addons/jasper_reports/controllers/main.py", line 106, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/opt/odoo14/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo14/odoo-custom-addons/jasper_reports/controllers/main.py", line 59, in report_routes
    jasper, output_type = report_jas.with_context(
  File "/opt/odoo14/odoo-custom-addons/jasper_reports/models/report_xml.py", line 189, in render_jasper
    jasper = r.execute()
  File "/opt/odoo14/odoo-custom-addons/jasper_reports/JasperReports/jasper_report_config.py", line 173, in execute
    pages = self.execute_report(
  File "/opt/odoo14/odoo-custom-addons/jasper_reports/JasperReports/jasper_report_config.py", line 259, in execute_report
    return server.execute(
  File "/opt/odoo14/odoo-custom-addons/jasper_reports/JasperReports/jasper_server.py", line 115, in execute
    self.start()
  File "/opt/odoo14/odoo-custom-addons/jasper_reports/JasperReports/jasper_server.py", line 105, in start
    with open(self.pidfile, 'w') as f:
PermissionError: [Errno 13] Permission denied: 'odoo-jasper.pid'

**Comment by hiren-serpentcs** [comment]
Hi @time2sales 

You need to give the write permission to the `jasper_reports` module.

**Comment by hiren-serpentcs** [comment]
Considering this resolved as there's no update
