### ISSUE TITLE
Jasper report Error

### ISSUE THREAD

**Issue by medhajoshi** [JayVora-SerpentCS/Jasperv8#23]
I am in the process of creating a basic report on Odoo 10 using JasperReport module by following instructions on the website -  http://www.serpentcs.com/wp-content/uploads/2015/03/jasper-report-Documentation.pdf 
Jasper report is created successfully but when I try to print the report, it gives following error - 

Odoo Warning - Warning
2
No such file or directory: (<type 'exceptions.OSError'>, OSError(2, 'No such file or directory'), <traceback object at 0x7fc9e0eda0e0>)

Here is the odoo-server.log -
2017-03-07 07:52:08,470 5855 INFO test odoo.addons.jasper_reports.jasper_report: Requested report: '/odoo/odoo-server/addons/jasper_reports/custom_reports/report1.jrxml'
2017-03-07 07:52:08,472 5855 INFO test odoo.addons.jasper_reports.jasper_report: Temporary data file: '/tmp/tmpicHYZ2'
2017-03-07 07:52:08,476 5855 WARNING test odoo.addons.jasper_reports.JasperReports.browse_data_generator: Field '' (path: currency_id/) does not                     exist in model 'res.currency'.
2017-03-07 07:52:08,476 5855 WARNING test odoo.addons.jasper_reports.JasperReports.browse_data_generator: Field '' (path: company_id/) does not                     exist in model 'res.company'.
2017-03-07 07:52:08,521 5855 ERROR test odoo.service.report: Exception: [Errno 2] No such file or directory: '/odoo/odoo-server/addons/jasper_reports/JasperReports/../java'
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/service/report.py", line 94, in go
    result, format = odoo.report.render_report(cr, uid, ids, object, datas, context)
  File "/odoo/odoo-server/odoo/report/__init__.py", line 19, in render_report
    return env['ir.actions.report.xml'].render_report(ids, name, data)
  File "/odoo/odoo-server/odoo/addons/base/ir/ir_actions.py", line 234, in render_report
    return report.create(self._cr, self._uid, res_ids, data, context=self._context)
  File "/odoo/odoo-server/addons/jasper_reports/jasper_report.py", line 311, in create
    return r.execute()
  File "/odoo/odoo-server/addons/jasper_reports/jasper_report.py", line 183, in execute
    sub_report_data_files)
  File "/odoo/odoo-server/addons/jasper_reports/jasper_report.py", line 272, in execute_report
    output_file, parameters)
  File "/odoo/odoo-server/addons/jasper_reports/JasperReports/jasper_server.py", line 110, in execute
    self.start()
  File "/odoo/odoo-server/addons/jasper_reports/JasperReports/jasper_server.py", line 97, in start
    process = subprocess.Popen(command, env=env, cwd=cwd)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory: '/odoo/odoo-server/addons/jasper_reports/JasperReports/../java'
2017-03-07 07:52:08,717 5855 ERROR test odoo.addons.web.controllers.main: An exception occured during an http request
Traceback (most recent call last):
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 68, in wrap
    return f(*args, **kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1445, in index
    request.session.db, request.session.uid, request.session.password, report_id])
  File "/odoo/odoo-server/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/odoo/odoo-server/odoo/service/report.py", line 35, in dispatch
    res = fn(db, uid, *params)
  File "/odoo/odoo-server/odoo/service/report.py", line 142, in exp_report_get
    return _check_report(report_id)
  File "/odoo/odoo-server/odoo/service/report.py", line 120, in _check_report
    raise UserError('%s: %s' % (exc.message, exc.traceback))
UserError: (u"2\nNo such file or directory: (<type 'exceptions.OSError'>, OSError(2, 'No such file or directory'), <traceback object at 0x7fc9e14993b0>)", None)
2017-03-07 07:52:08,720 5855 INFO test werkzeug: 127.0.0.1 - - [07/Mar/2017 07:52:08] "POST /web/report HTTP/1.1" 500 -
2017-03-07 07:52:09,349 5855 DEBUG ? odoo.service.server: cron1 polling for jobs

**Comment by medhajoshi** [comment]
Copied java libs from JasperReports 8.0 to JasperReports 10.0.
After copying java libs, I could save the jasper report on odoo 10 but got groovy evaluation error and uuid error while printing the report. The workaround to these errors is given on -
http://www.serpentcs.com/wp-content/uploads/2015/03/jasper-report-Documentation.pdf
Need to fix following 
1. java libs ishould be part of JasperReports 10.0 bundle
2. fix groovy evaluation error 
3. Fix uuid error

**Comment by hiren-serpentcs** [comment]
OSError: [Errno 2] No such file or directory: '/odoo/odoo-server/addons/jasper_reports/JasperReports/../java'
It seems like the Java path issue, java libs are not exists in your directory.

@medhajoshi please follow this documentation 
[Jasper Report Documentation](http://www.serpentcs.com/web/content/1980)
Thanks.
