### ISSUE TITLE
jasper repors on odoo 10 enterprise

### ISSUE THREAD

**Issue by medhajoshi** [JayVora-SerpentCS/Jasperv8#24]
We installed jasper reports on odoo 10 enterprise.
We attached a file sale_order.jrxml in custom reports and tried to get printout of sale order.
But we are getting error as below

### **## '**list' object is not callable: (<type 'exceptions.TypeError'>, TypeError("'list' object is not callable",), <traceback object at 0x7f465afa15f0>)**** 

**2017-03-30 09:25:01,402 856 INFO odooe odoo.addons.jasper_reports.jasper_report: Requested report: '/odoo/odoo-server/addons/jasper_reports/demo/sale_order_report.jrxml'
2017-03-30 09:25:01,403 856 INFO odooe odoo.addons.jasper_reports.jasper_report: Temporary data file: '/tmp/tmpuB35KI'
2017-03-30 09:25:01,404 856 ERROR odooe odoo.service.report: Exception: 'list' object is not callable
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/service/report.py", line 94, in go
    result, format = odoo.report.render_report(cr, uid, ids, object, datas, context)
  File "/usr/lib/python2.7/dist-packages/odoo/report/__init__.py", line 19, in render_report
return env['ir.actions.report.xml'].render_report(ids, name, data)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_actions.py", line 234, in render_report
    return report.create(self._cr, self._uid, res_ids, data, context=self._context)
  File "/odoo/odoo-server/addons/jasper_reports/jasper_report.py", line 311, in create
    return r.execute()
  File "/odoo/odoo-server/addons/jasper_reports/jasper_report.py", line 134, in execute
    generator.generate(data_file)
  File "/odoo/odoo-server/addons/jasper_reports/JasperReports/browse_data_generator.py", line 315, in generate
    relations = self.report.relations()
TypeError: 'list' object is not callable**

We are not getting any error on odoo 10 community for the same report.

Medha Joshi

**Comment by JayVora-SerpentCS** [comment]
@medhajoshi We have not checked the reports on Enterprise yet. This could be due to diff module on Enterprise. We would need your contribution. Should you need any support, we can help you professionally. Hence, we are closing.
