### ISSUE TITLE
error odoo v10

### ISSUE THREAD

**Issue by rcgdiax** [JayVora-SerpentCS/Jasperv8#26]
Traceback (most recent call last):
  File "/opt/odoo/server/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/server/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/server/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/server/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/server/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/server/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/server/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/server/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/server/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/server/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/server/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/server/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/server/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/server/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/server/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/server/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/server/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/server/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/server/odoo/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/server/odoo/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/server/odoo/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/odoo/server/odoo/tools/convert.py", line 710, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_model.py", line 1196, in _update
    record = record.create(values)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_ui_view.py", line 360, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/odoo/server/odoo/models.py", line 3829, in create
    self._fields[key].determine_inverse(record)
  File "/opt/odoo/server/odoo/fields.py", line 999, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/odoo/server/odoo/addons/base/ir/ir_ui_view.py", line 220, in _inverse_arch
    view.write(data)
  File "/opt/odoo/server/odoo/addons/base/ir/ir_ui_view.py", line 378, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/odoo/server/odoo/models.py", line 3555, in write
    self._write(old_vals)
  File "/opt/odoo/server/odoo/models.py", line 3706, in _write
    self._validate_fields(vals)
  File "/opt/odoo/server/odoo/models.py", line 1074, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
ParseError: "Error mientras se validavan las restricciones

Modelo no encontrado: jasper.create.data.template

Error de contexto:
Vista `Create Data Template`
[view_id: 971, xml_id: n/a, model: jasper.create.data.template, parent_id: n/a]
None" while parsing /opt/odoo/server/addons/jasper_reports/wizard/jasper_create_data_template.xml:4, near
<record id="view_pos_box_out" model="ir.ui.view">
        <field name="name">Create Data Template</field>
        <field name="model">jasper.create.data.template</field>
        <field name="type">form</field>
        <field name="arch" type="xml">
            <form name="Create Data Template">
                <group colspan="2">
                    <field name="model"/>
                    <field name="depth"/>
                    <field name="data" filename="filename" readonly="1"/>
                    <field name="filename" invisible="1"/>
                </group>
                <footer>
                    <button name="action_create_xml" string="Create" type="object" class="oe_highlight">
                        <i class="fa fa-check" aria-hidden="true"/>
                    </button>
                    <button special="cancel" string="Close" class="oe_highlight"/>
                </footer>
            </form>
        </field>
    </record>

**Comment by JayVora-SerpentCS** [comment]
The issue does not seem appearing. Reopen if it happens again.
