### ISSUE TITLE
Taxes subreport in invoice report

### ISSUE THREAD

**Issue by JuaniFreedoo** [JayVora-SerpentCS/Jasperv8#33]
When try print jasper invoice with subreport for taxes:

2017-11-07 00:38:31,836 27079 INFO SecurDemo odoo.addons.jasper_reports.jasper_report: Requested report: '/home/juani/odoo/v10/custom_addons/jasper_reports/custom_reports/facturajuani.jrxml'
2017-11-07 00:38:31,838 27079 INFO SecurDemo odoo.addons.jasper_reports.jasper_report: Temporary data file: '/tmp/tmpOibfi1'
2017-11-07 00:38:31,838 27079 ERROR SecurDemo odoo.service.report: Exception: 'str' object is not callable
Traceback (most recent call last):
  File "/home/juani/odoo/v10/server/odoo/service/report.py", line 94, in go
    result, format = odoo.report.render_report(cr, uid, ids, object, datas, context)
  File "/home/juani/odoo/v10/server/odoo/report/__init__.py", line 19, in render_report
    return env['ir.actions.report.xml'].render_report(ids, name, data)
  File "/home/juani/odoo/v10/odoo/odoo/addons/base/ir/ir_actions.py", line 234, in render_report
    return report.create(self._cr, self._uid, res_ids, data, context=self._context)
  File "/home/juani/odoo/v10/custom_addons/jasper_reports/jasper_report.py", line 311, in create
    return r.execute()
  File "/home/juani/odoo/v10/custom_addons/jasper_reports/jasper_report.py", line 142, in execute
    if sub_report.language() == 'xpath':
TypeError: 'str' object is not callable
2017-11-07 00:38:32,082 27079 ERROR SecurDemo odoo.addons.web.controllers.main: An exception occured during an http request
Traceback (most recent call last):
  File "/home/juani/odoo/v10/odoo/addons/web/controllers/main.py", line 70, in wrap
    return f(*args, **kwargs)
  File "/home/juani/odoo/v10/odoo/addons/web/controllers/main.py", line 1477, in index
    request.session.db, request.session.uid, request.session.password, report_id])
  File "/home/juani/odoo/v10/server/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/home/juani/odoo/v10/server/odoo/service/report.py", line 35, in dispatch
    res = fn(db, uid, *params)
  File "/home/juani/odoo/v10/server/odoo/service/report.py", line 142, in exp_report_get
    return _check_report(report_id)
  File "/home/juani/odoo/v10/server/odoo/service/report.py", line 120, in _check_report
    raise UserError('%s: %s' % (exc.message, exc.traceback))
UserError: (u'\'str\' object is not callable: (<type \'exceptions.TypeError\'>, TypeError("\'str\' object is not callable",), <traceback object at 0x7fa948f25ea8>)', None)

**Comment by JayVora-SerpentCS** [comment]
You should have:

` <subreportExpression class="java.lang.String"><![CDATA[$P{SUBREPORT_DIR} + "report_name.jasper"]]></subreportExpression>`
