### ISSUE TITLE
jasper reports odoo error

### ISSUE THREAD

**Issue by osboer** [JayVora-SerpentCS/Jasperv8#50]
I get this error :
: (<type 'exceptions.IOError'>, IOError(13, '\xe6\x9d\x83\xe9\x99\x90\xe4\xb8\x8d\xe5\xa4\x9f'), <traceback object at 0x7fd56f708ab8>) 
 ODOO V10.0

**Comment by JayVora-SerpentCS** [comment]
@osboer Can you specify the steps please?

**Comment by osboer** [comment]
Click Print and make a mistake！

**Comment by osboer** [comment]
WindowsError: [Error 2] 
2018-05-05 11:20:32,487 7232 ERROR DEMO odoo.addons.web.controllers.main: An exception occured during an http request
Traceback (most recent call last):
  File "D:\OdooDev\odoo10\addons\web\controllers\main.py", line 73, in wrap
    return f(*args, **kwargs)
  File "D:\OdooDev\odoo10\addons\web\controllers\main.py", line 1487, in index
    report_struct = exp_report_get(request.session.db, request.session.uid, report_id)
  File "D:\OdooDev\odoo10\odoo\service\report.py", line 142, in exp_report_get
    return _check_report(report_id)
  File "D:\OdooDev\odoo10\odoo\service\report.py", line 120, in _check_report
    raise UserError('%s: %s' % (exc.message, exc.traceback))
UserError: (u"2\n: (<type 'exceptions.WindowsError'>, WindowsError(2, ''), <traceback object at 0x0AAE7E90>)", '')
2018-05-05 11:20:32,496 7232 INFO DEMO werkzeug: 127.0.0.1 - - [05/May/2018 11:20:32] "POST /web/report HTTP/1.1" 500 -

**Comment by JayVora-SerpentCS** [comment]
@saif-serpentcs @hiren-serpentcs

**Comment by hiren-serpentcs** [comment]
@osboer I have printed the report with both v10 and v11 in Windows system and it works perfect as expected.

[v10 Report](https://drive.google.com/file/d/1GcrrplSfi4As2IIUzUK7rr-dCeRKRXvu/view?usp=sharing)

[v11 Report](https://drive.google.com/file/d/1MbDby9XFC9mh3QEraf7LGwvRruQkUT8R/view?usp=sharing)

Make sure the java path was configured properly and the Jasper Server can be initialized or not.

Thanks.
