### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by gjokao** [JayVora-SerpentCS/Jasperv8#61]
I have installed jasper_reports for Odoo 11 on Windows but when I try to open the demo sale order report it gives me the error : 

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\addons\base\ir\ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\http.py", line 820, in dispatch
    r = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\addons\report_xlsx\controllers\main.py", line 43, in report_routes
    reportname, docids, converter, **data
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\addons\jasper_reports\controllers\main.py", line 58, in report_routes
    context).render_jasper(docids, data=data)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\addons\jasper_reports\report_xml.py", line 115, in render_jasper
    return r.execute()
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\addons\jasper_reports\jasper_report.py", line 179, in execute
    sub_report_data_files)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\addons\jasper_reports\jasper_report.py", line 267, in execute_report
    output_file, parameters)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\addons\jasper_reports\JasperReports\jasper_server.py", line 110, in execute
    self.start()
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\addons\jasper_reports\JasperReports\jasper_server.py", line 97, in start
    process = subprocess.Popen(command, env=env, cwd=cwd)
  File "C:\Program Files (x86)\Odoo 11.0e\python\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Odoo 11.0e\python\lib\subprocess.py", line 992, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

I have put the value 'C:/Program Files (x86)/Odoo 11.0e/server/odoo/addons/jasper_reports/java' on java path field in Company Configuration.
Could you help what am I doing wrong?

**Comment by hiren-serpentcs** [comment]
Hello gjokao,
Thanks for reaching us.
The problem might be with your Java version or Java system path.
Can you please tell us the java version you are using?

**Comment by gjokao** [comment]
I'm using java version 1.7

**Comment by hiren-serpentcs** [comment]
Can you please verify your system path for Java?

**Comment by gjokao** [comment]
I verified the system path and fixed it. I also changed the java version to 1.8 due to another error I got and now it works :)
Thank you very much!

**Comment by Abdullah-GXS** [comment]
i am also using java version 1.8 but i am still getting error "FileNotFoundError: [WinError 2] The system cannot find the file specified". I dont know what should i change in my path, right now path is "C:\odoo\myaddon\jasper_reports\java"
Please help
