### ISSUE TITLE
blank page after installing jasper for odoo 10 on windows 7

### ISSUE THREAD

**Issue by UsamaIDT** [JayVora-SerpentCS/Jasperv8#97]
I have created a new database for odoo 10 and while installing jasper report app I got the error shown below 
![image](https://user-images.githubusercontent.com/55101379/64548338-b7f8c100-d32e-11e9-952e-e8174e472db1.png)

I have continued installation and the effects of installation ( java path in companies and jasper reports in menu ) appears correctly.

I restarted odoo service and  after that I got the blank page. The odoo log file has these errors :
2019-09-09 16:02:43,144 5688 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "werkzeug\serving.py", line 177, in run_wsgi
    
  File "werkzeug\serving.py", line 165, in execute
    
  File "D:\Program Files (x86)\Odoo 10.0\server\odoo\service\server.py", line 247, in app
    return self.app(e, s)
  File "D:\Program Files (x86)\Odoo 10.0\server\odoo\service\wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "D:\Program Files (x86)\Odoo 10.0\server\odoo\service\wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "D:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 1325, in __call__
    self.load_addons()
  File "D:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 1346, in load_addons
    m = __import__('odoo.addons.' + module)
  File "D:\Program Files (x86)\Odoo 10.0\server\odoo\modules\module.py", line 81, in load_module
    execfile(modfile, new_mod.__dict__)
  File "d:\Program Files (x86)\Odoo 10.0\server\odoo\addons\jasper_reports\__init__.py", line 38, in <module>
    from . import websrv_lib
  File "d:\Program Files (x86)\Odoo 10.0\server\odoo\addons\jasper_reports\websrv_lib.py", line 35, in <module>
    from SimpleHTTPServer import SimpleHTTPRequestHandler
ImportError: No module named SimpleHTTPServer

   Thanks for help

**Comment by SerpentCS** [comment]
@UsamaIDT We will do the needful, thanks.

**Comment by SerpentCS** [comment]
@hiren-serpentcs

**Comment by hiren-serpentcs** [comment]
Hello @UsamaIDT, 

Can you please make sure that you're running the Odoo server on Python2.x?

if you're running the server on Python2.x then the error is telling you that SimpleHTTPServer needs to be in your PYTHONPATH. You either need to install it or if it is installed in a non-standard location, modify your PYTHONPATH environment variable to include it - however, this would be a bit of a strange (though not impossible) situation since that module is normally included in Python2.x.

Thanks

**Comment by hiren-serpentcs** [comment]
@JayVora-SerpentCS 

We can assume this is fixed and close the issue.

@UsamaIDT   you can reopen the issue if it's not fixed.
